shared:
    image: golang
    environment:
        GOPATH: /sd/workspace

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - glide: |
                export PATH=$PATH:$GOPATH/bin
                go get -v github.com/Masterminds/glide
            - install: glide install
            - vet: go vet ./...
            - gofmt: "find . -name '*.go' | xargs gofmt -s -w"
            - test: GOCACHE=off go test ./... -p 1
            # The emitter file is changed by a test, but we want to ignore it
            - ignore-git: git update-index --assume-unchanged data/emitter
            # Ensure we can compile
            - build: go build -a -o /dev/null
            # Test cross-compiling as well
            - test-release: "curl -sL https://git.io/goreleaser | bash -s -- --snapshot"

    publish:
        requires: [main]
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - glide: |
                export PATH=$PATH:$GOPATH/bin
                go get -v github.com/Masterminds/glide
            - get: glide install
            - tag: ./ci/git-tag.sh
            - release: "curl -sL https://git.io/goreleaser | bash"
        secrets:
            # Pushing tags to Git
            - GIT_KEY
            # Pushing releases to GitHub
            - GITHUB_TOKEN
