shared:
    image: golang:1.14
    environment:
        GO111MODULE: on
jobs:
    main:
        environment:
            SD_SONAR_OPTS:  "-Dsonar.sources=./ -Dsonar.exclusions=**/*_test.go,**/vendor/** -Dsonar.tests=./ -Dsonar.test.inclusions=**/*_test.go -Dsonar.test.exclusions=**/vendor/** -Dsonar.go.coverage.reportPaths=${SD_ARTIFACTS_DIR}/coverage.out -Dsonar.go.tests.reportPaths=${SD_ARTIFACTS_DIR}/report.json"
        requires: [~commit, ~pr]
        steps:
            - gover: go version
            - install: |
                go mod download
                go mod vendor
            - vet: go vet ./...
            - gofmt: (! gofmt -d . | grep '^')
            - test: gotestsum --format testname --jsonfile ${SD_ARTIFACTS_DIR}/report.json -- -coverprofile=${SD_ARTIFACTS_DIR}/coverage.out ./...
            # Ensure we can compile
            - build: go build -a -o /dev/null
            # Test cross-compiling as well
            - test-release: "curl -sL https://git.io/goreleaser | bash -s -- --snapshot"

    publish:
        requires: [main]
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - get: go mod download
            - tag: ./ci/git-tag.sh
            - release: "curl -sL https://git.io/goreleaser | bash"
        secrets:
            # Pushing tags to Git
            - GIT_KEY
            # Pushing releases to GitHub
            - GITHUB_TOKEN
