jobs:
  main:
    image: golang
    steps:
      - ls: ls
      - loop: ./run.sh
      - get: go get -t ./...
      - vet: go vet ./...
      - gofmt: "find . -name '*.go' | xargs gofmt -s -w"
      - test: go test ./...
      - build: go build -a -o launch
