shared:
    image: golang:1.10
    environment:
        GOPATH: /sd/workspace

jobs:
    main:
        requires: [~pr, ~commit]
        environment:
            SD_SONAR_OPTS: "-Dsonar.sources=./  -Dsonar.exclusions=**/*_test.go,**/sonar-scanner*/** -Dsonar.go.coverage.reportPaths=/sd/workspace/artifacts/coverage.out"
        steps:
            - glide: |
                export PATH=$PATH:$GOPATH/bin
                go get -v github.com/Masterminds/glide
            - install: glide install
            - vet: go vet ./...
            - gofmt: "find . -name '*.go' | xargs gofmt -s -w"
            - gover: go version
            - test: GOCACHE=off go test -coverprofile=${SD_ARTIFACTS_DIR}/coverage.out -coverpkg=./...
            # The emitter file is changed by a test, but we want to ignore it
            - ignore-git: git update-index --assume-unchanged data/emitter
            # Ensure we can compile
            - build: go build -a -o /dev/null
            # Test cross-compiling as well
            - test-release: "curl -sL https://git.io/goreleaser | bash -s -- --snapshot"

    publish:
        requires: [main]
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - glide: |
                export PATH=$PATH:$GOPATH/bin
                go get -v github.com/Masterminds/glide
            - get: glide install
            - tag: ./ci/git-tag.sh
            - release: "curl -sL https://git.io/goreleaser | bash"
        secrets:
            # Pushing tags to Git
            - GIT_KEY
            # Pushing releases to GitHub
            - GITHUB_TOKEN
